baseURL: "https://self-taught-developer.com"
theme: "even"
title: "Self-Taught Developer"
defaultContentLanguage: "en"
preserveTaxonomyNames: true
enableRobotsTXT: true
enableEmoji: true

enableGitInfo: false # use git commit log to generate lastmod record # 可根据 Git 中的提交生成最近更新记录。

# Syntax highlighting by Chroma. NOTE: Don't enable `highlightInClient` and `chroma` at the same time!
pygmentsOptions: "linenos=table"
pygmentsCodefences: true
pygmentsUseClasses: true
pygmentsCodefencesGuessSyntax: true


hasCJKLanguage: false     # has chinese/japanese/korean ?
paginate: 5
copyright: "Christian Schleifer"

author:
  name: "Christian Schleifer"

sitemap:
  changefreq: "weekly"
  priority: 0.5
  filename: "sitemap.xml"

menu:
  main:
    - name: Imprint
      url: "/imprint/"
      weight: 1
    - name: Privacy Policy
      url: "/privacy-policy/"
      weight: 2
    - name: About
      url: "/about/"
      weight: 3

markup:
  tableOfContents:
    startLevel: 1
  goldmark:
    renderer:
      unsafe: true

params:
  version: "4.x"           # Used to give a friendly message when you have an incompatible update
  debug: false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda
  since: "2021"            # Site creation time          # 站点建立时间

  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle: "Self-Taught Developer"        # default: the title value    # 默认值: 上面设置的title值
  keywords: ["Hugo", "theme","even"]
  description: >
      Welcome to my blog. My name is Christian. I'm a 28-years-old software engineer living in Munich. I studied medicine and 
      have never undergone a formal computer science education. In this blog I want to write about tech and computer science concepts
      I'm currently learning about. I also want to provide some guidance on how to become a self-taught developer who 
      doesn't scare away from looking under the hood of abstractions.

  # paginate of archives, tags and categories
  archivePaginate: 50

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse: "2006-01-02"

  # show word count and read time ?
  moreMeta: true

  # Syntax highlighting by highlight.js
  highlightInClient: false